name = "BayesFlux"
uuid = "c2416e8a-86ea-414a-9a91-c37c770c1547"
authors = ["Enrico Wegner <wegner1996@gmail.com>"]
version = "0.2.1"

[deps]
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReTest = "e0db7c4e-2690-44b9-bad6-7687da720f89"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
# julia = "1.6 - 1.8"
julia = "1.6 - 1.9"
Bijectors = "0.10.3 - 0.10.7"
ChainRules = "1.39.1 - 1.46.1"
Distributions = "0.2 -  0.25.65"
DistributionsAD = "0.6"
Flux = "0.13"
MCMCChains = "5"
MLUtils = "0.2"
Optimisers = "0.2"
Parameters = "0.12"
ProgressBars = "1.4"
ProgressMeter = "1.7"
ReTest = "0.3"
StatsBase = "0.33"
StatsFuns = "1"
StatsPlots = "0.15"
Zygote = "0.6.41 - 0.6.54"

